name: fsm-extension-installer
version: 0.2.6
id: d17f0e6f-73fd-496b-b5a2-307d8ec362cc
description: "A simple addon to enable installing FSM extension on Kyma"
displayName: "FSM Extension Installer For Kyma"
providerDisplayName: "FSM"
documentationURL: https://github.com/SAP-samples/fsm-extension-installer-kyma/blob/master/README.md
tags: FSM, extension-installer, 0.2.6, broker
