name: fsm-extension-installer
version: 0.3.2
id: 37a29a73-f27b-41b1-9355-a5ec6ff15945
description: "A simple addon to enable installing FSM extension on Kyma"
displayName: "FSM Extension Installer For Kyma"
providerDisplayName: "FSM"
documentationURL: https://github.com/SAP-samples/fsm-extension-installer-kyma/blob/master/README.md
tags: FSM, extension-installer, 0.3.2, broker
